### PR TITLE
update to latest zig

### PR DESCRIPTION
**Pull request by joachimschmidt557**
Update the code to the latest zig from master

### CODE REVIEW

**Comment by tiehuis** [comment]
Great, thanks!

**Comment by joachimschmidt557** [comment]
No problem. Some tests are still failing though because allocated memory is not freed completely.

**Comment by tiehuis** [comment]
I presume this is because of new changes with the testing allocator checking for leaks? Might have a look at this soon.

**Comment by joachimschmidt557** [comment]
Yes, `testing.allocator` detects some leaks.

**Pull request merged**
