### PR TITLE
Leak free tests

### PR DESCRIPTION
**Pull request by kivikakk**
(This also includes #6.)

`zig build test` now runs without reporting any memory leaks.

### CODE REVIEW

**Comment by kivikakk** [comment]
Seeing double-frees in actual use/outside test context.

**Comment by LemonBoy** [comment]
> Seeing double-frees in actual use/outside test context.

Do you have a test case or a repo that show the double free problem?

**Comment by tiehuis** [comment]
I merged this commit externally here: https://github.com/tiehuis/zig-regex/commit/864f08aa8ca2bbe5e2835334bc60e6bf1750610f

I hit test leak failures when testing so merged even though a draft. Thanks.

**Comment by kivikakk** [comment]
Ta! :heart:

**Pull request closed without merging**
